name: dart_jsonwebtoken
description: A dart implementation of the famous javascript library 'jsonwebtoken'.
version: 1.0.1
repository: https://github.com/jonasroussel/jsonwebtoken
homepage: https://github.com/jonasroussel/jsonwebtoken#readme

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  rsa_pkcs: ^1.1.3
  pointycastle: ^1.0.2
