name: dart_jsonwebtoken
description: A dart implementation of the famous javascript library 'jsonwebtoken'.
version: 0.2.1
repository: https://github.com/jonasroussel/jsonwebtoken
homepage: https://github.com/jonasroussel/jsonwebtoken#readme

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
